spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Daniel0017
    username: root
    url: jdbc:mysql://localhost:3306/fornecedor
